// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbUNZK3aOOZaCSQjcBH6ngkwrB6Xhm32M',
    appId: '1:319498713309:web:e365fe7570bfd27bcd4334',
    messagingSenderId: '319498713309',
    projectId: 'mikky-mynotes',
    authDomain: 'mikky-mynotes.firebaseapp.com',
    storageBucket: 'mikky-mynotes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9xl5Em4T9ralHQDK_Drig0iMOVuTevkk',
    appId: '1:319498713309:android:d5f48b502b672079cd4334',
    messagingSenderId: '319498713309',
    projectId: 'mikky-mynotes',
    storageBucket: 'mikky-mynotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrHiFrxa1R-jEKwP26tjyO_7mnuOhFhc4',
    appId: '1:319498713309:ios:bfe88d1c182efb8ccd4334',
    messagingSenderId: '319498713309',
    projectId: 'mikky-mynotes',
    storageBucket: 'mikky-mynotes.appspot.com',
    iosClientId: '319498713309-ior4ljdphkqllrepeasadvqbaccaboi1.apps.googleusercontent.com',
    iosBundleId: 'com.mikky.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrHiFrxa1R-jEKwP26tjyO_7mnuOhFhc4',
    appId: '1:319498713309:ios:29a55151d2efcbb6cd4334',
    messagingSenderId: '319498713309',
    projectId: 'mikky-mynotes',
    storageBucket: 'mikky-mynotes.appspot.com',
    iosClientId: '319498713309-03inffsp5c0m9mm8chq7lotnfvr3qok3.apps.googleusercontent.com',
    iosBundleId: 'com.mikky.mynotes.RunnerTests',
  );
}
